#!/bin/bash

declare -a data="seed"
declare -a session=1
declare -a num_class=3



for subj in {1..15}; do
	for iter in {1..5}; do
		seed=$(($((100*$iter))+123));

		echo "Method: RSDA  Session:" $session "  Subject: " $subj		
		python3 main.py --dataset $data --target $subj --gpu_id 0 --num_class $num_class --max_iter1 2000 --max_iter2 1000 --seed $seed --lr_a 0.001 --lr_b 0.0001 --batch_size 560 --session $session --radius 10.0 --stages 3 --bottleneck_dim 256

		echo ""
		echo ""
	done
done



